// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.Logging;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class OverlayImageOnPDF extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __Overlay;
	private system.proxies.FileDocument Overlay;
	private IMendixObject __BaseDocument;
	private system.proxies.FileDocument BaseDocument;
	private java.lang.Long x;
	private java.lang.Long y;

	public OverlayImageOnPDF(IContext context, IMendixObject Overlay, IMendixObject BaseDocument, java.lang.Long x, java.lang.Long y)
	{
		super(context);
		this.__Overlay = Overlay;
		this.__BaseDocument = BaseDocument;
		this.x = x;
		this.y = y;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Overlay = __Overlay == null ? null : system.proxies.FileDocument.initialize(getContext(), __Overlay);

		this.BaseDocument = __BaseDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __BaseDocument);

		// BEGIN USER CODE
		// create a PDDocument for the base file
		IMendixObject baseFileDocument = BaseDocument.getMendixObject();
		PDDocument pdBaseDoc = PDDocument.load(Core.getFileDocumentContent(getContext(), baseFileDocument));
		// get the file of the image to overlay
		IMendixObject overlayFileDocument = Overlay.getMendixObject();
		PDImageXObject pdImage = PDImageXObject.createFromByteArray(pdBaseDoc, 
				Core.getFileDocumentContent(getContext(), __Overlay).readAllBytes(), null);
		// draw the image on the base PDDocument
		PDPageContentStream cs = new PDPageContentStream(pdBaseDoc, pdBaseDoc.getPage(0), PDPageContentStream.AppendMode.APPEND, true);
		cs.drawImage(pdImage, x, y);
		cs.close();
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		pdBaseDoc.save(baos);
		try (InputStream overlayedContent = new ByteArrayInputStream(baos.toByteArray())) {
//			Logging.trace(LOGNODE, "Store result in original document");
			Core.storeFileDocumentContent(getContext(), baseFileDocument, overlayedContent);
		}
		return true;
		
//		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OverlayImageOnPDF";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
